### ISSUE TITLE
Known issue with multiple class-based resources

### ISSUE THREAD

**Issue by juliamwang6** [Azure/nxtools#15]
Known issue: you currently cannot use two different kinds of class-based resources in the same mof file. We are actively working with the PowerShell team to fix this.

**Comment by SteveL-MSFT** [comment]
The known workaround for this limitation is that each class-based resource needs to have their own prefix for common types/enums like `File_Ensure` instead of just `Ensure`.

**Comment by mgreenegit** [comment]
Closing now that the workaround is publily documented

**Comment by juliamwang6** [comment]
[like]  Julia Wang reacted to your message:
________________________________
