### ISSUE TITLE
nxScript

### ISSUE THREAD

**Issue by nickelTyle** [Azure/nxtools#22]
are there any plans to incorporate the equivalent of nx module's nxScript Resource into the nxTools module? As far as I can tell there is not currently an nxScript-like resource available for DSC 3 + Linux. It would be useful in many cases including refreshing the Grub bootloader config on Debian-based distros.

**Comment by Ram1622** [comment]
@gurrajatwal, I am attempting to manage Linux from PowerShell using the NXTools module. To execute a shell script from PowerShell, I employ the NXScript command provided by the NXTools module. However, I have encountered an issue where the NXScript command is not recognized and results in an error. This problem prevents me from executing shell scripts as intended.
